# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: libvarlink.spec

# add or remove files that should be synced
synced_files:
    - libvarlink.spec
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: libvarlink
# downstream (Fedora) RPM package name
downstream_package_name: libvarlink
